# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnNotepad' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/Yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  # Pods for rnNotepad
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'
  pod 'react-native-maps', path: "../node_modules/react-native-maps"
  

  target 'rnNotepadTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnNotepad-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnNotepad-tvOS

  target 'rnNotepad-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
